version: '3'
services:
  'proxy':
    image: 'skadinad/proxy'
    ports:
      - '80:80'
      - '443:443'
    expose:
      - '80'
    restart: unless-stopped
  'frontend':
    image: 'skadinad/frontend-server'
    ports:
      - '9000:80' # TODO: dev only!
    expose:
      - '80'
    depends_on:
      - 'backend'
    environment:
      BACKEND_HOST: 'backend' # http://backend/...
    restart: unless-stopped
  'backend':
    image: 'skadinad/backend-server'
    ports:
      - '8000:80' # TODO: dev only!
    expose:
      - '80'
    environment:
      DUID: '1000'
      DGID: '1000'
      NGINX_CLIENT_MAX_BODY_SIZE: '20m'
    volumes:
      - 'grav-data:/var/www/grav/user'
    restart: unless-stopped
volumes:
  'grav-data':