absolute_urls: false
custom_base_url: '/backend'
session:
  path: '/backend'

home:
  alias: '/home'

# todo: never_cache_twig: true?
# https://learn.getgrav.org/17/content/headers#never-cache-twig

pages:
  theme: mostly-json
  markdown:
    extra: false
  process:
    markdown: true
    twig: false
  types: [html,htm,xml,txt,json,rss,atom,csv]
  expires: 300 # FOR DEVELOPMENT! default is 7 days

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

images:
  seofriendly: true # nicer image names 

twig:
  cache: false
  debug: true
  auto_reload: true
  autoescape: true

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_module_pipeline: false
  js_minify: true

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
gpm:
  verify_peer: true
